### ISSUE TITLE
Additional use cases / examples

### ISSUE THREAD

**Issue by aaronransley** [getify/revocable-queue#7]
Thank you for this nuanced tech! I’m curious if there are plans to add some in-place examples of this queuing technology in a larger context? By this I mean: case studies or examinations of this tech being applied to specific facets of a whole application?

The low level docs are great, but some higher level “when could this benefit you” kind of writing might be helpful as well!

**Comment by getify** [comment]
Would love to have more stuff like that as a contribution!

The main two use-cases I had in an application I was building are described in these two sections:

* https://github.com/getify/revocable-queue/blob/master/README.md#lazyzip

* https://github.com/getify/revocable-queue/blob/master/README.md#eventstate

So, in that respect, I think these examples are already more "real world" rather than "low level". But it would be nice to have others provide additional use-cases. :)

**Comment by aaronransley** [comment]
Ah, I totally skimmed past these examples, mistaking them for method documentation. Thanks so much!
